version: '2.2'
services:
###
### Core Inferno Services
###
  inferno_web:
    build:
      context: ./
    mem_limit: 1500m
    restart: unless-stopped
    volumes:
      - ./resources:/opt/inferno/resources
      - ./_site:/opt/inferno/_site
    depends_on:
      # - validator_service
      - test_kit_validator_service
      - inferno_db
  inferno_worker:
    build:
      context: ./
    command: /opt/inferno/worker.sh
    mem_limit: 2000m
    restart: unless-stopped
    volumes:
      - ./resources:/opt/inferno/resources
    depends_on:
      - redis
      - inferno_db
  inferno_worker_2:
    build:
      context: ./
    command: /opt/inferno/worker.sh
    mem_limit: 2000m
    restart: unless-stopped
    volumes:
      - ./resources:/opt/inferno/resources
    depends_on:
      - redis
      - inferno_db
  inferno_db:
    image: postgres:14.1-alpine
    mem_limit: 600m
    shm_size: 1g
    restart: unless-stopped
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: inferno_production
###
### Required Services
###
  nginx:
    image: nginx
    volumes:
      - ./_site:/var/www/inferno/public/
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      # - /etc/ssl/certs/inferno:/etc/ssl/certs/inferno:ro
      # to use tls on localhost for development, comment out above line and uncomment below
      - ./config/development-certs:/etc/ssl/certs/inferno:ro
    ports:
      - "80:80"
      - "443:443"
    command: [nginx, '-g', 'daemon off;']
    mem_limit: 100m
    restart: unless-stopped
    depends_on:
      - fhir_validator_app
  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
    mem_limit: 100m
    restart: unless-stopped
###
### Validators
###
  # validator_service:
  #   image: infernocommunity/fhir-validator-service:v2.2.1
  #   volumes:
  #     - ./lib/inferno_platform_template/igs:/home/igs
  #   mem_limit: 14500m
  #   restart: unless-stopped
  test_kit_validator_service:
    image: infernocommunity/fhir-validator-service:v2.3.2
    volumes:
      - ./lib/inferno_deployment/igs:/home/igs
    mem_limit: 11500m
    restart: unless-stopped
  fhir_validator_app:
    image: infernocommunity/fhir-validator-app
    depends_on:
      - test_kit_validator_service
    environment:
      EXTERNAL_VALIDATOR_URL: /validatorapi
      VALIDATOR_BASE_PATH: /validator
    mem_limit: 100m
    restart: unless-stopped
###
### Other Services
### Example of using the 'Inferno Reference Server below'
###

# inferno_reference_server:
#   image: infernocommunity/inferno-reference-server:v2.2.0
#   mem_limit: 3000m
#   restart: unless-stopped
#   ports:
#     - "8080:8080"
#   volumes:
#     - ./fhir_resources:/var/lib/jetty/resources
#   environment:
#     - CUSTOM_BEARER_TOKEN=SAMPLE_TOKEN
#     - READ_ONLY=true
#   depends_on:
#     - db
# db:
#   image: postgres:9.6-alpine
#   environment:
#     - POSTGRES_HOST_AUTH_METHOD=trust
#   volumes:
#     - fhir-pgdata:/var/lib/postgresql/data
#   restart: unless-stopped
#   mem_limit: 600m
# volumes:
#  fhir-pgdata:
